name: nary_tree
version: 0.0.2
description: Simple N-ary Tree
repository: https://github.com/TabooSun/dart_nary_tree
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.11.0
  git: ^2.0.0
  args: ^2.0.0
  path: ^1.8.0
  flutter_test: 
    sdk: flutter
flutter: null
